BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for processor-sdk-linux/processor-sdk-linux-09_00_00_06"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for processor-sdk-linux/processor-sdk-linux-09_00_00_06"

DISTRO_FEATURES:append = " virtualization"
ARAGO_BRAND = "foundational_sdk"
