BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for processor-sdk-linux/processor-sdk-linux-10_01_08_01"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for processor-sdk-linux/processor-sdk-linux-10_01_08_01"

DISTRO_FEATURES:append = " virtualization"
DISTROOVERRIDES:append = ":foundational"
