BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for processor-sdk-linux/processor-sdk-linux-09_01_00_07"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for processor-sdk-linux/processor-sdk-linux-09_01_00_07"

DISTRO_FEATURES:append = " virtualization"
