BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for coresdk/coresdk-10.01.10-selinux-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for coresdk/coresdk-10.01.10-selinux-config"

DISTRO_FEATURES:append = " acl xattr pam selinux"
