BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for arago-master-next-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for arago-master-next-config"

OVERRIDES:append = ":recipe-${@os.path.basename(d.getVar('FILE'))}"
