BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for arago-master-selinux-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for arago-master-selinux-config"

DISTRO_FEATURES:append = " acl xattr pam selinux"
