BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for arago-scarthgap-10x-next-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for arago-scarthgap-10x-next-config"

TI_PREFERRED_BSP = "ti-6_6"
OVERRIDES:append = ":recipe-${@os.path.basename(d.getVar('FILE'))}"
BRANCH:recipe-linux-ti-staging_6.6.bb = "ti-linux-6.6.y-cicd"
BRANCH:recipe-linux-ti-staging-rt_6.6.bb = "ti-rt-linux-6.6.y-cicd"
BRANCH:recipe-u-boot-ti-staging_2024.04.bb = "ti-u-boot-2024.04-next"
