BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for arago-scarthgap-10x-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for arago-scarthgap-10x-config"

TI_PREFERRED_BSP = "ti-6_6"
