BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for arago-kirkstone-next-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for arago-kirkstone-next-config"

OVERRIDES:append = ":recipe-${@os.path.basename(d.getVar('FILE'))}"
BRANCH:recipe-linux-ti-staging_6.1.bb = "ti-linux-6.1.y-cicd"
BRANCH:recipe-linux-ti-staging-rt_6.1.bb = "ti-rt-linux-6.1.y-cicd"
BRANCH:recipe-linux-ti-staging-systest_6.1.bb = "ti-linux-6.1.y-cicd"
GIT_BRANCH:recipe-ti-k3-secdev_git.bb = "master-next"
BRANCH:recipe-u-boot-ti-staging_2023.04.bb = "ti-u-boot-2023.04-next"
