BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for processor-sdk/processor-sdk-scarthgap-selinux-11.01.05.03-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for processor-sdk/processor-sdk-scarthgap-selinux-11.01.05.03-config"

DISTRO_FEATURES:append = " acl xattr pam selinux"
