BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for processor-sdk-analytics/processor-sdk-analytics-selinux-11.01.07.05-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for processor-sdk-analytics/processor-sdk-analytics-selinux-11.01.07.05-config"

DISTRO_FEATURES:append = " acl xattr pam selinux"
